/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_CAT_MESSAGE_ID_HEADER__
#define __RFX_CAT_MESSAGE_ID_HEADER__

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_SEND_ENVELOPE_COMMAND)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_SEND_TERMINAL_RESPONSE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM_WITH_RESULT_CODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_REPORT_STK_SERVICE_IS_RUNNING)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_SEND_ENVELOPE_WITH_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_SEND_RESPONSE_BY_CMDTYPE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_EVENT_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STK_QUERY_CPIN_STATE)

RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_SESSION_END)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_PROACTIVE_COMMAND)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_EVENT_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_CALL_SETUP)
RFX_MSG_ID_EXPN(RFX_MSG_URC_SIM_REFRESH)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_CC_ALPHA_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_SETUP_MENU_RESET)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_CALL_CTRL)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_TRIGGER_OTASP)
RFX_MSG_ID_EXPN(RFX_MSG_URC_STK_CPIN_STATE)

RFX_MSG_ID_EXPN(RFX_MSG_EVENT_STK_IS_RUNNING)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_STK_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_STK_QUERY_CPIN_STATE)
// BIP @{
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_BIP_SEND_CONFIRM_INFO)
// BIP @}
// BTSAP @{
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SIM_SAP_TRANSFER_CARD_READER_STATUS)
// BTSAP @}
#endif
