/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_CALLCONTROL_MESSAGE_ID_HEADER__
#define __RFX_CALLCONTROL_MESSAGE_ID_HEADER__

RFX_MSG_ID_EXPN(RFX_MSG_EVENT_CNAP_UPDATE)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_CLEAR_CLCCNAME)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_EXIT_EMERGENCY_CALLBACK_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_URC_CC_GSM_SIM_ECC)
RFX_MSG_ID_EXPN(RFX_MSG_URC_CC_C2K_SIM_ECC)
RFX_MSG_ID_EXPN(RFX_MSG_URC_CC_ECC_NUMBER_TEST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_CURRENT_CALLS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_EMERGENCY_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_HANGUP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_HANGUP_WAITING_OR_BACKGROUND)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CONFERENCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_UDUB)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LAST_CALL_FAIL_CAUSE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DTMF)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ANSWER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DTMF_START)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DTMF_STOP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEPARATE_CONNECTION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_MUTE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_MUTE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_EXPLICIT_CALL_TRANSFER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_TTY_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_TTY_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_RESPONSE_CALL_STATE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_SUPP_SVC_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_SUPP_SVC_NOTIFICATION_EX)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CALL_RING)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_RINGBACK_TONE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_RESEND_INCALL_MUTE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_HANGUP_ALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_FORCE_RELEASE_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CALL_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LOCAL_EMERGENCY_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LOCAL_SET_ECC_SERVICE_CATEGORY)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CRSS_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_INCOMING_CALL_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CALL_ADDITIONAL_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CIPHER_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_SPEECH_CODEC_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ESPEECH)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_ECC_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LOCAL_CURRENT_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECC_PREFERRED_RAT)

/// C2K specific start
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE)    // AT+VP
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE)  // AT+VP?
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CDMA_FLASH)                               // AT+CFSH
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CDMA_BURST_DTMF)                          // AT+VTS
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CDMA_CALL_WAITING)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CDMA_INFO_REC)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CDMA_CALL_ACCEPTED)
/// C2K specific end

RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CALL_INFO_INDICATION)

/// redial local message id @{
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_NO_EMERGENCY_CALLBACK_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_EMERGENCY_REDIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_EMERGENCY_SESSION_END)
/// @}

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_ECC_NUM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_ECC_NUM)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ECC_NUM)

// hangup request with reason
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_HANGUP_WITH_REASON)

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LOCAL_FAKE_ACCEPT)         // GWSD
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LOCAL_FAKE_REJECT)         // GWSD
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_FAKE_INCOMING_CALL_FAILURE)  // GWSD
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_FAKE_ACCEPT)                 // GWSD
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_FAKE_REJECT)                 // GWSD

RFX_MSG_ID_EXPN(RFX_MSG_URC_EMERGENCY_NUMBER_LIST)

// M: RTT @{
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_RTT_MODE)
// @}

// M: GWSD @{
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_GWSD_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_GWSD_CALL_VALID)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_GWSD_IGNORE_CALL_INTERVAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_GWSD_KEEP_ALIVE_PDCP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_GWSD_KEEP_ALIVE_IPDATA)
// @}

#endif
