/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_DATA_MESSAGE_ID_HEADER__
#define __RFX_DATA_MESSAGE_ID_HEADER__
// Request msg id
// ID=53008
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ALLOW_DATA)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SETUP_DATA_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DEACTIVATE_DATA_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DATA_CALL_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_LAST_DATA_CALL_FAIL_CAUSE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_INITIAL_ATTACH_APN)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_DATA_PROFILE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SYNC_DATA_SETTINGS_TO_MD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RESET_MD_DATA_RETRY_COUNT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_START_LCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STOP_LCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_PULL_LCEDATA)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_LTE_ACCESS_STRATUM_REPORT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_LTE_UPLINK_DATA_TRANSFER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CLEAR_ALL_PDN_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_FD_MODE)
/// M: Ims Data Framework {@
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_BEARER_STATE_CONFIRM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_IMS_BEARER_NOTIFICATION)
/// @}
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RESEND_SYNC_DATA_SETTINGS_TO_MD)
// PS/CS attach
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DATA_CONNECTION_ATTACH)
// PS/CS detach
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DATA_CONNECTION_DETACH)
// Cleanup all connections
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RESET_ALL_CONNECTIONS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_LINK_CAPACITY_REPORTING_CRITERIA)

// Recovery allow data for temp data switch.
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RECOVERY_ALLOW_DATA)

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_PREFERRED_DATA_MODEM)
// Device state
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_DEVICE_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_START_KEEPALIVE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_STOP_KEEPALIVE)

// URC msg id
RFX_MSG_ID_EXPN(RFX_MSG_URC_DATA_CALL_LIST_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_REMOVE_RESTRICT_EUTRAN)
RFX_MSG_ID_EXPN(RFX_MSG_URC_MD_DATA_RETRY_COUNT_RESET)
RFX_MSG_ID_EXPN(RFX_MSG_URC_LCEDATA_RECV)
RFX_MSG_ID_EXPN(RFX_MSG_URC_LTE_ACCESS_STRATUM_STATE_CHANGE)
/// M: Ims Data Framework {@
RFX_MSG_ID_EXPN(RFX_MSG_URC_IMS_BEARER_STATE_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_URC_IMS_BEARER_INIT)
RFX_MSG_ID_EXPN(RFX_MSG_URC_IMS_DATA_INFO_NOTIFY)
/// @}
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_PCO_DATA)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_PCO_DATA_AFTER_ATTACHED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_LINK_CAPACITY_ESTIMATE)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NETWORK_REJECT_CAUSE)
RFX_MSG_ID_EXPN(RFX_MSG_URC_QUALIFIED_NETWORK_TYPES_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_MOBILE_DATA_USAGE)
RFX_MSG_ID_EXPN(RFX_MSG_URC_KEEPALIVE_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NW_LIMIT)

// Event id
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_ACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_OR_ME_DEACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_PDN_ACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_PDN_DEACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_MODIFY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_REACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_ME_PDN_ACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_ME_PDN_DEACT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_PDN_CHANGE)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_UT_TEST)  // M: UT Test.
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_LCE_STATUS_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_LTE_ACCESS_STRATUM_STATE_CHANGE)
/// M: Ims Data Framework {@
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_IMS_PDN_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_PCSCF_ADDRESS_DISCOVERY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_QUALIFIED_NETWORK_TYPES_CHANGED)
/// @}
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_QUERY_PCO_WITH_URC)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_QUERY_PCO_WITH_AID)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_LINK_CAPACITY_ESTIMATE)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_NETWORK_REJECT_CAUSE)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_REQ_DATA_CONTEXT_IDS)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_RSP_DATA_CONTEXT_IDS)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_SEND_QUALIFIED_NETWORK_TYPES_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_QUERY_SELF_IA)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_MOBILE_DATA_USAGE_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_KEEPALIVE_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_DATA_NW_LIMIT_NOTIFY)
#endif
