/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_GSM_SMS_MESSAGE_ID_HEADER__
#define __RFX_GSM_SMS_MESSAGE_ID_HEADER__

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_SMS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_SMS_EXPECT_MORE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_WRITE_SMS_TO_SIM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DELETE_SMS_ON_SIM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_REPORT_SMS_MEMORY_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_SMS_SIM_MEM_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SMS_ACKNOWLEDGE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_SMSC_ADDRESS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_SMSC_ADDRESS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_SMS_PARAMS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_SMS_PARAMS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GSM_GET_BROADCAST_LANGUAGE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GSM_SET_BROADCAST_LANGUAGE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GSM_SMS_BROADCAST_ACTIVATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_ETWS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_REMOVE_CB_MESSAGE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_GSM_SMS_BROADCAST_ACTIVATION)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_NEW_SMS)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_NEW_BROADCAST_SMS)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_ETWS_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_URC_SMS_READY_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_URC_SIM_SMS_STORAGE_FULL)
RFX_MSG_ID_EXPN(RFX_MSG_URC_ME_SMS_STORAGE_FULL)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_NEW_SMS_ON_SIM)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_NEW_SMS_STATUS_REPORT)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_SMS_NEW_SMS_ERR_ACK)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_SMS_NOTIFY_SMS_READY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SMS_ACKNOWLEDGE_INTERNAL)

#endif
