/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_MOBILE_WIFI_MESSAGE_ID_HEADER__
#define __RFX_MOBILE_WIFI_MESSAGE_ID_HEADER__

// Request msg id
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WIFI_ENABLED)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WIFI_ASSOCIATED)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WFC_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WIFI_SIGNAL_LEVEL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_GEO_LOCATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WIFI_IP_ADDRESS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_EMERGENCY_ADDRESS_ID)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_NATT_KEEP_ALIVE_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WIFI_PING_RESULT)
/// M: Notify ePDG screen state
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_NOTIFY_EPDG_SCREEN_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_SSAC_STATUS)

// URC msg id
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_MOBILE_WIFI_ROVEOUT)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_MOBILE_WIFI_HANDOVER)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ACTIVE_WIFI_PDN_COUNT)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_WIFI_RSSI_MONITORING_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_WIFI_PDN_ERROR)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_REQUEST_GEO_LOCATION)
RFX_MSG_ID_EXPN(RFX_MSG_URC_WFC_PDN_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_NATT_KEEP_ALIVE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_WIFI_PING_REQUEST)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_WIFI_PDN_OOS)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_WIFI_LOCK)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_SSAC_STATUS)
#endif
