/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_OEM_MESSAGE_ID_HEADER__
#define __RFX_OEM_MESSAGE_ID_HEADER__

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_BASEBAND_VERSION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_OEM_HOOK_RAW)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_OEM_HOOK_STRINGS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DEVICE_IDENTITY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_HARDWARE_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_ACTIVITY_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_MOBILEREVISION_AND_IMEI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_MODEM_THERMAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_MODEM_THERMAL)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_OEM_HOOK_RAW)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_HARDWARE_CONFIG_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ABNORMAL_EVENT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_TRM)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_IMS_DATA)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_IMEI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_IMEISV)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_SHARED_KEY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_UPDATE_SIM_LOCK_SETTINGS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_SIM_LOCK_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RESET_SIM_LOCK_SETTINGS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_MODEM_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_URC_SIM_MELOCK_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_GET_SHARED_KEY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_UPDATE_SIM_LOCK_SETTINGS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_GET_SIM_LOCK_VERSION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_RESET_SIM_LOCK_SETTINGS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_GET_MODEM_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_GET_MODEM_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_GET_API_VERSION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ATT_GET_SIM_SLOTS)
RFX_MSG_ID_EXPN(RFX_MSG_URC_ATT_SIM_LOCK_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_TX_POWER)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_TX_POWER_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_TX_POWER_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_PHONE_CAPABILITY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ENABLE_DSDA_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_DSDA_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ON_DSDA_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ROUTE_CERTIFICATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ROUTE_AUTH)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ENABLE_CAPABILITY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ABORT_CERTIFICATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_CAPABILITY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_SAR_IND)
#endif
