/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_PHB_MESSAGE_ID_HEADER__
#define __RFX_PHB_MESSAGE_ID_HEADER__

RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_PHB_STORAGE_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_WRITE_PHB_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_PHB_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_UPB_CAPABILITY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_EDIT_UPB_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DELETE_UPB_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_UPB_GAS_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_UPB_GRP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_WRITE_UPB_GRP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_PHB_STRING_LENGTH)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_PHB_MEM_STORAGE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_PHB_MEM_STORAGE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_PHB_ENTRY_EXT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_WRITE_PHB_ENTRY_EXT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_UPB_AVAILABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_EMAIL_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_SNE_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_ANR_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_READ_UPB_AAS_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_PHB_CURRENT_STORAGE_RESET)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_PHB_CURRENT_STORAGE_RESET)
RFX_MSG_ID_EXPN(RFX_MSG_URC_PHB_READY_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_PHONEBOOK_READY)
#endif
