/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RFX_SUPP_SERV_MESSAGE_ID_HEADER__
#define __RFX_SUPP_SERV_MESSAGE_ID_HEADER__

RFX_MSG_ID_EXPN(RFX_MSG_EVENT_URC_CRING_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_URC_ECPI133_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_UNSOL_ON_USSD)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_UNSOL_ON_USSI)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_SET_XCAP_CONFIG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_USSD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CANCEL_USSD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_CLIR)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CLIR)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_CALL_FORWARD_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CALL_FORWARD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CALL_WAITING)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_CALL_BARRING)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CALL_BARRING)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CHANGE_BARRING_PASSWORD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_CLIP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CLIP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_SUPP_SVC_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_COLP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_COLP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_COLR)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_COLR)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_CNAP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SEND_USSI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CANCEL_USSI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_CALL_WAITING)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ON_USSD)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CALL_FORWARDING)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ON_USSI)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ON_XUI)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ON_VOLTE_SUBSCRIPTION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_CALL_FORWARD_IN_TIME_SLOT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CALL_FORWARD_IN_TIME_SLOT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_XCAP_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_CALL_WAITING_ATCI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RESET_SUPP_SERV)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SETUP_XCAP_USER_AGENT_STRING)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_SS_PROPERTY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_USSD_DOMAIN_INFO_REQ)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_USSD_DOMAIN_INFO_ACK)
#endif
