/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef RIL_OP12IMSCONFIGDATA_H
#define RIL_OP12IMSCONFIGDATA_H

#define CONFIG_VALUE(x, y, z) {ImsConfigItem::x, y, z},

CONFIG_VALUE(IMS_CONFIG_VOCODER_AMRMODESET, IMS_CONFIG_UNIT_NONE, "7")
CONFIG_VALUE(IMS_CONFIG_VOCODER_AMRWBMODESET, IMS_CONFIG_UNIT_NONE, "2")
CONFIG_VALUE(IMS_CONFIG_SIP_SESSION_TIMER, IMS_CONFIG_UNIT_SECONDS, "300")
CONFIG_VALUE(IMS_CONFIG_MIN_SE, IMS_CONFIG_UNIT_SECONDS, "300")
CONFIG_VALUE(IMS_CONFIG_CANCELLATION_TIMER, IMS_CONFIG_UNIT_SECONDS, "6")
CONFIG_VALUE(IMS_CONFIG_TDELAY, IMS_CONFIG_UNIT_SECONDS, "5")
CONFIG_VALUE(IMS_CONFIG_SILENT_REDIAL_ENABLE, IMS_CONFIG_UNIT_NONE, "1")
CONFIG_VALUE(IMS_CONFIG_SIP_T1_TIMER, IMS_CONFIG_UNIT_SECONDS, "3")
CONFIG_VALUE(IMS_CONFIG_SIP_T2_TIMER, IMS_CONFIG_UNIT_SECONDS, "16")
CONFIG_VALUE(IMS_CONFIG_SIP_TF_TIMER, IMS_CONFIG_UNIT_SECONDS, "30")
CONFIG_VALUE(IMS_CONFIG_VLT_SETTING_ENABLED, IMS_CONFIG_UNIT_NONE, "0")
CONFIG_VALUE(IMS_CONFIG_LVC_SETTING_ENABLED, IMS_CONFIG_UNIT_NONE, "1")
CONFIG_VALUE(IMS_CONFIG_DOMAIN_NAME, IMS_CONFIG_UNIT_NONE, "vzims.com")
CONFIG_VALUE(IMS_CONFIG_SMS_FORMAT, IMS_CONFIG_UNIT_NONE, "1")
CONFIG_VALUE(IMS_CONFIG_SMS_OVER_IP, IMS_CONFIG_UNIT_NONE, "1")
CONFIG_VALUE(IMS_CONFIG_PUBLISH_TIMER, IMS_CONFIG_UNIT_SECONDS, "1200")
CONFIG_VALUE(IMS_CONFIG_PUBLISH_TIMER_EXTENDED, IMS_CONFIG_UNIT_SECONDS, "86400")
CONFIG_VALUE(IMS_CONFIG_CAPABILITIES_CACHE_EXPIRATION, IMS_CONFIG_UNIT_SECONDS, "7776000")
CONFIG_VALUE(IMS_CONFIG_AVAILABILITY_CACHE_EXPIRATION, IMS_CONFIG_UNIT_SECONDS, "60")
CONFIG_VALUE(IMS_CONFIG_CAPABILITIES_POLL_INTERVAL, IMS_CONFIG_UNIT_SECONDS, "625000")
CONFIG_VALUE(IMS_CONFIG_SOURCE_THROTTLE_PUBLISH, IMS_CONFIG_UNIT_SECONDS, "60")
CONFIG_VALUE(IMS_CONFIG_MAX_NUMENTRIES_IN_RCL, IMS_CONFIG_UNIT_NONE, "100")
CONFIG_VALUE(IMS_CONFIG_CAPAB_POLL_LIST_SUB_EXP, IMS_CONFIG_UNIT_SECONDS, "30")
CONFIG_VALUE(IMS_CONFIG_GZIP_FLAG, IMS_CONFIG_UNIT_NONE, "1")
CONFIG_VALUE(IMS_CONFIG_EAB_SETTING_ENABLED, IMS_CONFIG_UNIT_NONE, "0")
CONFIG_VALUE(IMS_CONFIG_VOICE_OVER_WIFI_ROAMING, IMS_CONFIG_UNIT_NONE, "0")
CONFIG_VALUE(IMS_CONFIG_VOICE_OVER_WIFI_MODE, IMS_CONFIG_UNIT_NONE, "2")
CONFIG_VALUE(IMS_CONFIG_CAPABILITY_DISCOVERY_ENABLED, IMS_CONFIG_UNIT_NONE, "1")
CONFIG_VALUE(IMS_CONFIG_PUBLISH_ERROR_RETRY_TIMER, IMS_CONFIG_UNIT_SECONDS, "21600")
CONFIG_VALUE(IMS_CONFIG_VOICE_OVER_WIFI_MDN, IMS_CONFIG_UNIT_NONE, "")

#endif  // RIL_OP12IMSCONFIGDATA_H
