/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef RIL_IMSCONFIGITEMS_H
#define RIL_IMSCONFIGITEMS_H
#define CONFIG_DATA(x, y, z) {ImsConfigItem::x, {ImsConfigItem::x, ImsCfgMimeType::y, z}},

CONFIG_DATA(IMS_CONFIG_VOCODER_AMRMODESET, STRING, "")
CONFIG_DATA(IMS_CONFIG_VOCODER_AMRWBMODESET, STRING, "")
CONFIG_DATA(IMS_CONFIG_SIP_SESSION_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_MIN_SE, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_CANCELLATION_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_TDELAY, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SILENT_REDIAL_ENABLE, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_T1_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_T2_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_TF_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VLT_SETTING_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_LVC_SETTING_ENABLED, INTEGER, "video_over_ps_support")
CONFIG_DATA(IMS_CONFIG_DOMAIN_NAME, STRING, "")
CONFIG_DATA(IMS_CONFIG_SMS_FORMAT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SMS_OVER_IP, INTEGER, "sms_over_ip")
CONFIG_DATA(IMS_CONFIG_PUBLISH_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_CAPABILITY_DISCOVERY_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_PUBLISH_TIMER_EXTENDED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_CAPABILITIES_CACHE_EXPIRATION, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_AVAILABILITY_CACHE_EXPIRATION, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_CAPABILITIES_POLL_INTERVAL, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SOURCE_THROTTLE_PUBLISH, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_MAX_NUMENTRIES_IN_RCL, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_CAPAB_POLL_LIST_SUB_EXP, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_GZIP_FLAG, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_EAB_SETTING_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOICE_OVER_WIFI_ROAMING, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOICE_OVER_WIFI_MODE, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_MOBILE_DATA_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOLTE_USER_OPT_IN_STATUS, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_LBO_PCSCF_ADDRESS, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_KEEP_ALIVE_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_REGISTRATION_RETRY_BASE_TIME_SEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_REGISTRATION_RETRY_MAX_TIME_SEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SPEECH_START_PORT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SPEECH_END_PORT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_INVITE_REQ_RETX_INTERVAL_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_INVITE_RSP_WAIT_TIME_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_INVITE_RSP_RETX_WAIT_TIME_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_NON_INVITE_REQ_RETX_INTERVAL_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_NON_INVITE_TXN_TIMEOUT_TIMER_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_INVITE_RSP_RETX_INTERVAL_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_ACK_RECEIPT_WAIT_TIME_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_ACK_RETX_WAIT_TIME_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_NON_INVITE_REQ_RETX_WAIT_TIME_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SIP_NON_INVITE_RSP_RETX_WAIT_TIME_MSEC, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_AMR_WB_OCTET_ALIGNED_PT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_AMR_WB_BANDWIDTH_EFFICIENT_PT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_AMR_OCTET_ALIGNED_PT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_AMR_BANDWIDTH_EFFICIENT_PT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_DTMF_WB_PT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_DTMF_NB_PT, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_AMR_DEFAULT_MODE, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_SMS_PSI, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VIDEO_QUALITY, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOICE_OVER_WIFI_SETTING_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_TH_LTE1, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_TH_LTE2, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_TH_LTE3, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_TH_1x, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOWT_A, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOWT_B, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_T_EPDG_LTE, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_T_EPDG_WIFI, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_T_EPDG_1X, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VICE_SETTING_ENABLED, INTEGER, "call_pull_service")
CONFIG_DATA(IMS_CONFIG_RTT_SETTING_ENABLED, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_EPDG_ADDRESS, STRING, "epdg_identifier")
CONFIG_DATA(IMS_CONFIG_PUBLISH_ERROR_RETRY_TIMER, INTEGER, "")
CONFIG_DATA(IMS_CONFIG_VOICE_OVER_WIFI_MDN, STRING, "")
CONFIG_DATA(IMS_CONFIG_VOICE_DOMAIN_PREFERENCE, INTEGER, "")

#endif  // RIL_IMSCONFIGITEMS_H
